# Generated by Django 2.1.2 on 2018-10-19 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre1', models.CharField(max_length=60)),
                ('Nombre2', models.CharField(blank=True, max_length=60, null=True)),
                ('Apellido1', models.CharField(max_length=60)),
                ('Apellido2', models.CharField(blank=True, max_length=60, null=True)),
                ('FechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHistorialPaciente', models.DateField()),
                ('HistorialPaciente', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre1', models.CharField(max_length=60)),
                ('Nombre2', models.CharField(blank=True, max_length=60, null=True)),
                ('Apellido1', models.CharField(max_length=60, null=True)),
                ('Apellido2', models.CharField(blank=True, max_length=60)),
                ('FechaIngreso', models.DateField()),
                ('EstadoActivacion', models.CharField(choices=[('A', 'Activo'), ('N', 'NoActivo')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=60)),
                ('Contraseña', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=254)),
                ('idDocete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionFundapoex.Docente')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionFundapoex.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='historialpaciente',
            name='IdentificacionPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionFundapoex.Paciente'),
        ),
    ]
